CREATE TABLE IF NOT EXISTS todo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  description TEXT,
  due_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  -- completed BOOLEAN NOT NULL DEFAULT 0
);

-- Add initial data of +100 todo
INSERT INTO todo (task, description) VALUES 
('Buy Bread', 'Need more bread.'),
('Buy Butter', 'Need more butter.'),
('Go Outside', 'Outside'),
('Find Window', ''),
('Schedule Dentist', 'Call the dentist to schedule a cleaning.')
('Todo #1: Plan project strategy', 'Define scope, milestones, and resource allocation.'),
('Todo #2: Set up development environment', 'Install IDE, Go, and necessary dependencies.'),
('Todo #3: Initialize Cobra CLI', 'Run cobra-cli init and set up the root command.'),
('Todo #4: Implement database connection logic', 'Create NewDB provider for Fx or connect for CLI.'),
('Todo #5: Write 000001_initial.up.sql', 'Create the initial schema for the todo table.'),
('Todo #6: Run initial migration', 'Execute the "migrate up" command.'),
('Todo #7: Develop service layer', 'Implement business logic for creating and fetching todo.'),
('Todo #8: Create API endpoints', 'Define REST handlers for todo operations.'),
('Todo #9: Review code for module A', 'Perform peer review of the authentication module.'),
('Todo #10: Write unit tests for data access', 'Ensure 100% coverage for the repository methods.'),
('Todo #11: Configure logging (Zap)', 'Integrate structured logging into the application.'),
('Todo #12: Define configuration (Viper)', 'Set up config loading from YAML and environment.'),
('Todo #13: Refactor error handling', 'Use custom error types and standardize API responses.'),
('Todo #14: Set up CI/CD pipeline', 'Define Gitlab/GitHub actions for testing and deployment.'),
('Todo #15: Create documentation draft', 'Start writing the README and API specifications.'),
('Todo #16: Check email queue for notifications', 'Verify if scheduled emails are being processed.'),
('Todo #17: Optimize database queries', 'Analyze slow logs and add necessary indexes.'),
('Todo #18: Deploy to staging environment', 'Push the latest build to the staging server.'),
('Todo #19: Monitor application metrics', 'Check Prometheus/Grafana dashboard for initial load.'),
('Todo #20: Attend team stand-up meeting', 'Discuss yesterday\'s progress and today\'s plan.')
('Todo #1: Task for project phase 1', 'Generated task detail for testing data volume: Item 1 of 100.'),
('Todo #2: Task for project phase 1', 'Generated task detail for testing data volume: Item 2 of 100.'),
('Todo #3: Task for project phase 1', 'Generated task detail for testing data volume: Item 3 of 100.'),
('Todo #4: Task for project phase 1', 'Generated task detail for testing data volume: Item 4 of 100.'),
('Todo #5: Task for project phase 1', 'Generated task detail for testing data volume: Item 5 of 100.'),
('Todo #6: Task for project phase 1', 'Generated task detail for testing data volume: Item 6 of 100.'),
('Todo #7: Task for project phase 1', 'Generated task detail for testing data volume: Item 7 of 100.'),
('Todo #8: Task for project phase 1', 'Generated task detail for testing data volume: Item 8 of 100.'),
('Todo #9: Task for project phase 1', 'Generated task detail for testing data volume: Item 9 of 100.'),
('Todo #10: Task for project phase 1', 'Generated task detail for testing data volume: Item 10 of 100.'),
('Todo #11: Task for project phase 1', 'Generated task detail for testing data volume: Item 11 of 100.'),
('Todo #12: Task for project phase 1', 'Generated task detail for testing data volume: Item 12 of 100.'),
('Todo #13: Task for project phase 1', 'Generated task detail for testing data volume: Item 13 of 100.'),
('Todo #14: Task for project phase 1', 'Generated task detail for testing data volume: Item 14 of 100.'),
('Todo #15: Task for project phase 1', 'Generated task detail for testing data volume: Item 15 of 100.'),
('Todo #16: Task for project phase 1', 'Generated task detail for testing data volume: Item 16 of 100.'),
('Todo #17: Task for project phase 1', 'Generated task detail for testing data volume: Item 17 of 100.'),
('Todo #18: Task for project phase 1', 'Generated task detail for testing data volume: Item 18 of 100.'),
('Todo #19: Task for project phase 1', 'Generated task detail for testing data volume: Item 19 of 100.'),
('Todo #20: Task for project phase 1', 'Generated task detail for testing data volume: Item 20 of 100.'),
('Todo #21: Task for project phase 1', 'Generated task detail for testing data volume: Item 21 of 100.'),
('Todo #22: Task for project phase 1', 'Generated task detail for testing data volume: Item 22 of 100.'),
('Todo #23: Task for project phase 1', 'Generated task detail for testing data volume: Item 23 of 100.'),
('Todo #24: Task for project phase 1', 'Generated task detail for testing data volume: Item 24 of 100.'),
('Todo #25: Task for project phase 1', 'Generated task detail for testing data volume: Item 25 of 100.'),
('Todo #26: Task for project phase 2', 'Generated task detail for testing data volume: Item 26 of 100.'),
('Todo #27: Task for project phase 2', 'Generated task detail for testing data volume: Item 27 of 100.'),
('Todo #28: Task for project phase 2', 'Generated task detail for testing data volume: Item 28 of 100.'),
('Todo #29: Task for project phase 2', 'Generated task detail for testing data volume: Item 29 of 100.'),
('Todo #30: Task for project phase 2', 'Generated task detail for testing data volume: Item 30 of 100.'),
('Todo #31: Task for project phase 2', 'Generated task detail for testing data volume: Item 31 of 100.'),
('Todo #32: Task for project phase 2', 'Generated task detail for testing data volume: Item 32 of 100.'),
('Todo #33: Task for project phase 2', 'Generated task detail for testing data volume: Item 33 of 100.'),
('Todo #34: Task for project phase 2', 'Generated task detail for testing data volume: Item 34 of 100.'),
('Todo #35: Task for project phase 2', 'Generated task detail for testing data volume: Item 35 of 100.'),
('Todo #36: Task for project phase 2', 'Generated task detail for testing data volume: Item 36 of 100.'),
('Todo #37: Task for project phase 2', 'Generated task detail for testing data volume: Item 37 of 100.'),
('Todo #38: Task for project phase 2', 'Generated task detail for testing data volume: Item 38 of 100.'),
('Todo #39: Task for project phase 2', 'Generated task detail for testing data volume: Item 39 of 100.'),
('Todo #40: Task for project phase 2', 'Generated task detail for testing data volume: Item 40 of 100.'),
('Todo #41: Task for project phase 2', 'Generated task detail for testing data volume: Item 41 of 100.'),
('Todo #42: Task for project phase 2', 'Generated task detail for testing data volume: Item 42 of 100.'),
('Todo #43: Task for project phase 2', 'Generated task detail for testing data volume: Item 43 of 100.'),
('Todo #44: Task for project phase 2', 'Generated task detail for testing data volume: Item 44 of 100.'),
('Todo #45: Task for project phase 2', 'Generated task detail for testing data volume: Item 45 of 100.'),
('Todo #46: Task for project phase 2', 'Generated task detail for testing data volume: Item 46 of 100.'),
('Todo #47: Task for project phase 2', 'Generated task detail for testing data volume: Item 47 of 100.'),
('Todo #48: Task for project phase 2', 'Generated task detail for testing data volume: Item 48 of 100.'),
('Todo #49: Task for project phase 2', 'Generated task detail for testing data volume: Item 49 of 100.'),
('Todo #50: Task for project phase 2', 'Generated task detail for testing data volume: Item 50 of 100.'),
('Todo #51: Task for project phase 3', 'Generated task detail for testing data volume: Item 51 of 100.'),
('Todo #52: Task for project phase 3', 'Generated task detail for testing data volume: Item 52 of 100.'),
('Todo #53: Task for project phase 3', 'Generated task detail for testing data volume: Item 53 of 100.'),
('Todo #54: Task for project phase 3', 'Generated task detail for testing data volume: Item 54 of 100.'),
('Todo #55: Task for project phase 3', 'Generated task detail for testing data volume: Item 55 of 100.'),
('Todo #56: Task for project phase 3', 'Generated task detail for testing data volume: Item 56 of 100.'),
('Todo #57: Task for project phase 3', 'Generated task detail for testing data volume: Item 57 of 100.'),
('Todo #58: Task for project phase 3', 'Generated task detail for testing data volume: Item 58 of 100.'),
('Todo #59: Task for project phase 3', 'Generated task detail for testing data volume: Item 59 of 100.'),
('Todo #60: Task for project phase 3', 'Generated task detail for testing data volume: Item 60 of 100.'),
('Todo #61: Task for project phase 3', 'Generated task detail for testing data volume: Item 61 of 100.'),
('Todo #62: Task for project phase 3', 'Generated task detail for testing data volume: Item 62 of 100.'),
('Todo #63: Task for project phase 3', 'Generated task detail for testing data volume: Item 63 of 100.'),
('Todo #64: Task for project phase 3', 'Generated task detail for testing data volume: Item 64 of 100.'),
('Todo #65: Task for project phase 3', 'Generated task detail for testing data volume: Item 65 of 100.'),
('Todo #66: Task for project phase 3', 'Generated task detail for testing data volume: Item 66 of 100.'),
('Todo #67: Task for project phase 3', 'Generated task detail for testing data volume: Item 67 of 100.'),
('Todo #68: Task for project phase 3', 'Generated task detail for testing data volume: Item 68 of 100.'),
('Todo #69: Task for project phase 3', 'Generated task detail for testing data volume: Item 69 of 100.'),
('Todo #70: Task for project phase 3', 'Generated task detail for testing data volume: Item 70 of 100.'),
('Todo #71: Task for project phase 3', 'Generated task detail for testing data volume: Item 71 of 100.'),
('Todo #72: Task for project phase 3', 'Generated task detail for testing data volume: Item 72 of 100.'),
('Todo #73: Task for project phase 3', 'Generated task detail for testing data volume: Item 73 of 100.'),
('Todo #74: Task for project phase 3', 'Generated task detail for testing data volume: Item 74 of 100.'),
('Todo #75: Task for project phase 3', 'Generated task detail for testing data volume: Item 75 of 100.'),
('Todo #76: Task for project phase 4', 'Generated task detail for testing data volume: Item 76 of 100.'),
('Todo #77: Task for project phase 4', 'Generated task detail for testing data volume: Item 77 of 100.'),
('Todo #78: Task for project phase 4', 'Generated task detail for testing data volume: Item 78 of 100.'),
('Todo #79: Task for project phase 4', 'Generated task detail for testing data volume: Item 79 of 100.'),
('Todo #80: Task for project phase 4', 'Generated task detail for testing data volume: Item 80 of 100.'),
('Todo #81: Task for project phase 4', 'Generated task detail for testing data volume: Item 81 of 100.'),
('Todo #82: Task for project phase 4', 'Generated task detail for testing data volume: Item 82 of 100.'),
('Todo #83: Task for project phase 4', 'Generated task detail for testing data volume: Item 83 of 100.'),
('Todo #84: Task for project phase 4', 'Generated task detail for testing data volume: Item 84 of 100.'),
('Todo #85: Task for project phase 4', 'Generated task detail for testing data volume: Item 85 of 100.'),
('Todo #86: Task for project phase 4', 'Generated task detail for testing data volume: Item 86 of 100.'),
('Todo #87: Task for project phase 4', 'Generated task detail for testing data volume: Item 87 of 100.'),
('Todo #88: Task for project phase 4', 'Generated task detail for testing data volume: Item 88 of 100.'),
('Todo #89: Task for project phase 4', 'Generated task detail for testing data volume: Item 89 of 100.'),
('Todo #90: Task for project phase 4', 'Generated task detail for testing data volume: Item 90 of 100.'),
('Todo #91: Task for project phase 4', 'Generated task detail for testing data volume: Item 91 of 100.'),
('Todo #92: Task for project phase 4', 'Generated task detail for testing data volume: Item 92 of 100.'),
('Todo #93: Task for project phase 4', 'Generated task detail for testing data volume: Item 93 of 100.'),
('Todo #94: Task for project phase 4', 'Generated task detail for testing data volume: Item 94 of 100.'),
('Todo #95: Task for project phase 4', 'Generated task detail for testing data volume: Item 95 of 100.'),
('Todo #96: Task for project phase 4', 'Generated task detail for testing data volume: Item 96 of 100.'),
('Todo #97: Task for project phase 4', 'Generated task detail for testing data volume: Item 97 of 100.'),
('Todo #98: Task for project phase 4', 'Generated task detail for testing data volume: Item 98 of 100.'),
('Todo #99: Task for project phase 4', 'Generated task detail for testing data volume: Item 99 of 100.'),
('Todo #100: Task for project phase 4', 'Generated task detail for testing data volume: Item 100 of 100.');